#!/bin/bash

# PRODUCTION DEPLOYMENT CHECKLIST
# Mini Golf Every Day - Server Setup
# 
# Files to upload to your cPanel server:
# =====================================

echo "📋 PRODUCTION DEPLOYMENT CHECKLIST"
echo "=================================="
echo ""
echo "1. FILES TO UPLOAD TO YOUR SERVER:"
echo "   ✅ cron_wrapper.sh (main automation script)"
echo "   ✅ flask_app.py (updated with fallback logic)"
echo "   ✅ tiktok_automation.py (video manager - optional)"
echo "   ✅ tiktok_videos.json (current video database)"
echo "   ✅ .env (rename .env.production to .env on server)"
echo ""
echo "2. FILE PERMISSIONS TO SET ON SERVER:"
echo "   chmod 755 cron_wrapper.sh"
echo "   chmod 755 flask_app.py"
echo "   chmod 664 tiktok_videos.json"
echo "   chmod 644 .env"
echo ""
echo "3. ENVIRONMENT VARIABLES (in .env file):"
echo "   MGED_DOMAIN=https://minigolfevery.day"
echo "   MGED_API_KEY=_HHIKEGqH8ieN-J_Eh8QiaHyQmc_ThZv_ekDA9hueWU"
echo "   MGED_ENV=production"
echo ""
echo "4. CRON JOB TO SET UP IN CPANEL:"
echo "   Command: /home/username/public_html/cron_wrapper.sh"
echo "   Schedule: 0 */4 * * *  (every 4 hours)"
echo ""
echo "5. PYTHON PACKAGES NEEDED ON SERVER:"
echo "   - requests (usually pre-installed)"
echo "   - flask (for the API)"
echo ""
echo "6. TESTING:"
echo "   - Run ./cron_wrapper.sh manually first to test"
echo "   - Check cron.log for output"
echo "   - Verify tiktok_videos.json gets updated"
echo ""
echo "🎯 KEY IMPROVEMENTS MADE:"
echo "   ✅ Fixed environment variable handling"
echo "   ✅ Added fallback for yt-dlp failures"
echo "   ✅ Improved error logging and debugging"
echo "   ✅ Added file permission checks"
echo "   ✅ No longer requires yt-dlp on production server"
echo ""
echo "🚀 The automation should now work reliably on your cPanel server!"
