#!/bin/bash
# 🚀 Mini Golf Every Day - Upload Verification Script

echo "🎯 MINI GOLF EVERY DAY - SERVER UPLOAD CHECKLIST"
echo "================================================"
echo ""

echo "📋 ESSENTIAL FILES TO UPLOAD:"
echo "=============================="

echo ""
echo "🌐 MAIN WEBSITE FILES (Required):"
echo "  ✅ index.html          (Dynamic homepage - 9.8KB)"
echo "  ✅ watch.html          (Dynamic watch page - 19KB)"  
echo "  ✅ about.html          (About page)"
echo "  ✅ favicon.ico         (Site icon)"

echo ""
echo "🐍 PYTHON BACKEND (Required):"
echo "  ✅ flask_app.py        (Main Flask application)"
echo "  ✅ passenger_wsgi.py   (WSGI entry point)"
echo "  ✅ tiktok_automation.py (Core automation logic)"
echo "  ✅ requirements.txt    (Python dependencies)"
echo "  ✅ .htaccess          (URL routing)"

echo ""
echo "📊 DATA & AUTOMATION (Required):"
echo "  ✅ tiktok_videos.json  (178 videos - 46KB)"
echo "  ✅ cron_update.py     (Automation script)"
echo "  ✅ cron_wrapper.sh    (Cron job wrapper)"

echo ""
echo "📁 ASSET FOLDERS (Required):"
echo "  ✅ css/               (All stylesheets)"
echo "  ✅ images/            (All images/logos)"
echo "  ✅ js/                (JavaScript files)"

echo ""
echo "🔧 OPTIONAL HELPER FILES:"
echo "  ⚪ add_video.py       (Manual video addition)"
echo "  ⚪ debug.py           (Troubleshooting)"
echo "  ⚪ fetch_all_videos.py (Full re-sync tool)"

echo ""
echo "🚫 DO NOT UPLOAD:"
echo "  ❌ py311env/          (Virtual environment)"
echo "  ❌ *_backup_*.html    (Backup files)"
echo "  ❌ *_static.html      (Old static versions)"
echo "  ❌ *.log             (Log files)"

echo ""
echo "🎯 AFTER UPLOAD - TEST THESE URLS:"
echo "=================================="
echo "  🏠 https://minigolfevery.day/"
echo "  📺 https://minigolfevery.day/watch.html" 
echo "  🔗 https://minigolfevery.day/api/status"
echo "  📊 https://minigolfevery.day/api/videos"

echo ""
echo "⚡ EXPECTED RESULTS:"
echo "=================="
echo "  ✨ Homepage shows '178 videos and counting!'"
echo "  🔍 Watch page loads all 178 videos with search"
echo "  📱 Mobile-responsive design"
echo "  🔄 Auto-updates every 6 hours via cron"

echo ""
echo "🆘 IF SOMETHING BREAKS:"
echo "======================"
echo "  1. Check API endpoints first (/api/status)"
echo "  2. Verify tiktok_videos.json uploaded (46KB)"
echo "  3. Check browser console for JS errors"
echo "  4. SSH and check Python dependencies"

echo ""
echo "📞 Quick SSH Commands After Upload:"
echo "==================================="
echo "  pip install -r requirements.txt"
echo "  chmod +x cron_wrapper.sh"
echo "  crontab -e  # Add: 0 */6 * * * /path/to/cron_wrapper.sh"
